apiVersion: v1
kind: ReplicationController
metadata:
  name: atomix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: atomix
    spec:
      containers:
      - name: atomix
        image: 311873742948.dkr.ecr.us-east-1.amazonaws.com/atomix:latest
        env:
          - name: HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: "5000"
          - name: MODE
            value: "bootstrap"
          - name: PROVIDER
            value: "k8s"
        ports:
          - containerPort: 5000
        resources:
          limits:
            cpu: "250m"
      - name: kubernetes-api
        image: orbweb/kubectl
        command: ["kubectl", "proxy"]
        ports:
          - containerPort: 8001
