apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atomix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: atomix
        mode: join
    spec:
      containers:
      - name: atomix
        image: 311873742948.dkr.ecr.us-east-1.amazonaws.com/atomix:latest
        env:
          - name: HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: "5000"
          - name: MODE
            value: "join"
          - name: PROVIDER
            value: "k8s"
          - name: _JAVA_OPTIONS
            value: "-Xms2G -Xmx2G"
        ports:
          - containerPort: 5000
        resources:
          limits:
            cpu: 250m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 2Gi
      - name: kubernetes-api
        image: wernight/kubectl
        command: ["kubectl", "proxy"]
        ports:
          - containerPort: 8001
