atomix-1:
  image: atomix
  environment:
    HOST: r1.atomix.docker
    PORT: "5000"
    MODE: bootstrap
    PROVIDER: env
    NODES: r1.atomix.docker:5000,r2.atomix.docker:5001,r3.atomix.docker:5002
    DNSDOCK_NAME: r1
    DNSDOCK_IMAGE: atomix
atomix-2:
  image: atomix
  environment:
    HOST: r2.atomix.docker
    PORT: "5001"
    MODE: bootstrap
    PROVIDER: env
    NODES: r1.atomix.docker:5000,r2.atomix.docker:5001,r3.atomix.docker:5002
    DNSDOCK_NAME: r2
    DNSDOCK_IMAGE: atomix
atomix-3:
  image: atomix
  environment:
    HOST: r3.atomix.docker
    PORT: "5002"
    MODE: bootstrap
    PROVIDER: env
    NODES: r1.atomix.docker:5000,r2.atomix.docker:5001,r3.atomix.docker:5002
    DNSDOCK_NAME: r3
    DNSDOCK_IMAGE: atomix
